trigger:
  - dev

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python -m pip install --upgrade pip
      pip install robotframework robotframework-seleniumlibrary
    displayName: 'Instalar Python e dependências'

  - script: |
      # Instalar o Google Chrome
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo apt install ./google-chrome-stable_current_amd64.deb -y

      # Baixar o ChromeDriver compatível com o Chrome
      CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+" | head -1)
      CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r ".channels.Stable.downloads.chromedriver[] | select(.platform == \"linux64\") | select(.url | test(\"$CHROME_VERSION\")) | .url")
      wget -O chromedriver.zip $CHROMEDRIVER_VERSION
      unzip chromedriver.zip
      sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
      sudo chmod +x /usr/local/bin/chromedriver
    displayName: 'Instalar Chrome e ChromeDriver'

  - script: |
      robot -d results tests/
    displayName: 'Executar Testes Robot Framework'

  - task: PublishBuildArtifacts@1
    displayName: 'Publicar Resultados dos Testes'
    inputs:
      pathToPublish: results
      artifactName: TestResults
