trigger:
  - dev

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python -m pip install --upgrade pip
      pip install robotframework robotframework-seleniumlibrary
    displayName: 'Instalar Python e dependências'

  - script: |
      chmod +x drivers/chromedriver
      export PATH=$PATH:$(pwd)/drivers
      robot -d results tests/
    displayName: 'Executar Testes Robot Framework'

  - task: PublishBuildArtifacts@1
    displayName: 'Publicar Resultados dos Testes'
    inputs:
      pathToPublish: results
      artifactName: TestResults
