trigger:
  - dev

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python -m pip install --upgrade pip
      pip install robotframework robotframework-seleniumlibrary
    displayName: 'Instalar Python e dependências'

  - script: |
      sudo apt-get update
      sudo apt-get install -y wget unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo apt install -y ./google-chrome-stable_current_amd64.deb
      CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
      wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip || wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
      unzip chromedriver.zip
      sudo mv chromedriver /usr/local/bin/
      sudo chmod +x /usr/local/bin/chromedriver
    displayName: 'Instalar Chrome e ChromeDriver'

  - script: |
      robot -d results tests/
    displayName: 'Executar Testes Robot Framework'

  - task: PublishBuildArtifacts@1
    displayName: 'Publicar Resultados dos Testes'
    inputs:
      pathToPublish: results
      artifactName: TestResults
