name: Robot Framework CI

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: |
          mkdir -p results
          python -m robot tests/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results
