name: Robot Framework Tests

on:
  push:
    branches: [ dev ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/upload-artifact@v3.1.3

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y wget jq unzip

      - name: Instalar Google Chrome e ChromeDriver
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb -y

          CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+" | head -1)
          DRIVER_URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r ".channels.Stable.downloads.chromedriver[] | select(.platform == \"linux64\") | select(.url | test(\"$CHROME_VERSION\")) | .url")
          wget -O chromedriver.zip $DRIVER_URL
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Configurar Python e instalar libs
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary robotframework-browser
          rfbrowser init

      - name: Executar testes Robot Framework
        run: |
          robot --loglevel DEBUG -d results tests/login_tests.robot

      - name: Upload de artefatos
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: results
